name: BabeGame

options:
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 6.0

targets:
  BabeGame:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: BabeGame
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luowenxi76.BabeGame
        PRODUCT_NAME: BabeGame
        INFOPLIST_FILE: BabeGame/Supporting/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_ASSET_PATHS: "\"BabeGame/Preview Content\""
        GENERATE_INFOPLIST_FILE: NO
        SUPPORTS_MACCATALYST: NO
